#!/usr/bin/env python3
"""Generate FreeRADIUS and WireGuard configs from member YAML files.

Usage:
    python3 generate-configs.py [members_dir] [output_dir]

Security:
    Each member's realm is validated against its filename to prevent a member
    from injecting realms belonging to other domains.
"""

import glob
import os
import re
import sys
import yaml


def slug(realm: str) -> str:
    """Convert realm to a safe FreeRADIUS identifier (dots → dashes)."""
    return realm.replace(".", "-")


def validate_realm_vs_filename(realm: str, filepath: str):
    """
    Enforce that the realm declared in a member YAML matches the filename.
    Prevents a member from declaring realm sub.other.org inside their own file.
    Subdomains of their own realm are allowed (e.g. eduroam.example.org inside
    example.org.yml), but cross-domain declarations are blocked.
    """
    expected = os.path.basename(filepath)
    # Strip .sops.yml or .yml suffix
    expected = re.sub(r'\.sops\.yml$|\.yml$', '', expected)

    if realm != expected and not realm.endswith("." + expected):
        print(
            f"❌ SECURITY ERROR: {filepath} declares realm '{realm}' "
            f"but filename implies '{expected}' (or a subdomain of it).",
            file=sys.stderr,
        )
        sys.exit(1)


def main():
    members_dir = sys.argv[1] if len(sys.argv) > 1 else "members"
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "out"
    os.makedirs(output_dir, exist_ok=True)

    members = []
    for path in sorted(glob.glob(os.path.join(members_dir, "*.yml"))):
        with open(path) as f:
            m = yaml.safe_load(f)

        # Security: realm must match filename
        validate_realm_vs_filename(m["member"]["realm"], path)
        members.append(m)

    # --- clients.conf ---
    lines = [
        "# clients.conf — generated by generate-configs.py, DO NOT EDIT",
        "client localhost {",
        "    ipaddr = 127.0.0.1",
        "    secret = testing123",
        "    shortname = localhost",
        "}",
        "",
    ]
    for m in members:
        s = slug(m["member"]["realm"])
        lines += [
            f"# {m['member']['name']} ({m['member']['realm']})",
            f"client member_{s} {{",
            f"    ipaddr = {m['network']['mgmt_ip']}",
            f"    secret = {m['radius']['shared_secret']}",
            f"    shortname = {s}",
            "}",
            "",
        ]
    with open(os.path.join(output_dir, "clients.conf"), "w") as f:
        f.write("\n".join(lines))

    # --- proxy.conf ---
    lines = [
        "# proxy.conf — generated by generate-configs.py, DO NOT EDIT",
        "proxy server {",
        "    default_fallback = no",
        "}",
        "",
    ]
    for m in members:
        s = slug(m["member"]["realm"])
        realm = m["member"]["realm"]
        ip = m["network"]["mgmt_ip"]
        secret = m["radius"]["shared_secret"]
        port = m["radius"].get("port", 1812)
        status_check = m["radius"].get("status_check", "status-server")
        eap_note = ", ".join(m["radius"].get("eap_methods", []))
        lines += [
            f"# {m['member']['name']} ({realm}) — EAP: {eap_note}",
            f"home_server hs_{s} {{",
            "    type = auth+acct",
            f"    ipaddr = {ip}",
            f"    port = {port}",
            f"    secret = {secret}",
            f"    status_check = {status_check}",
            "    response_window = 20",
            "    check_interval = 30",
            "    check_timeout = 4",
            "    num_answers_to_alive = 3",
            "}",
            "",
            f"home_server_pool pool_{s} {{",
            "    type = fail-over",
            f"    home_server = hs_{s}",
            "}",
            "",
            f"realm {realm} {{",
            f"    pool = pool_{s}",
            "    nostrip",
            "}",
            "",
        ]
    lines += [
        "realm LOCAL {",
        "}",
        "",
        "realm NULL {",
        "    reject = yes",
        "}",
        "",
        "realm DEFAULT {",
        "    reject = yes",
        "}",
    ]
    with open(os.path.join(output_dir, "proxy.conf"), "w") as f:
        f.write("\n".join(lines))

    # --- WireGuard peers ---
    lines = ["# wg-peers.conf — generated by generate-configs.py, DO NOT EDIT", ""]
    for m in members:
        name = m["member"]["name"]
        realm = m["member"]["realm"]
        ip = m["network"]["mgmt_ip"]
        pubkey = m["network"]["wg_pubkey"]
        lines += [
            f"# {name} ({realm})",
            "[Peer]",
            f"PublicKey = {pubkey}",
            f"AllowedIPs = {ip}/32",
            "",
        ]
    with open(os.path.join(output_dir, "wg-peers.conf"), "w") as f:
        f.write("\n".join(lines))

    print(f"✓ Generated configs for {len(members)} member(s) → {output_dir}/")


if __name__ == "__main__":
    main()
